
OLED_ENABLE = yes
OLED_DRIVER = SSD1306
ENCODER_ENABLE = yes
CONSOLE_ENABLE = no
MOUSEKEY_ENABLE = yes
EXTRAKEY_ENABLE = yes
RGBLIGHT_ENABLE = no
SPLIT_KEYBOARD = yes
LTO_ENABLE = yes
TAP_DANCE_ENABLE = yes
VIA_ENABLED = yes